-- MySQL Script generated by MySQL Workbench
-- Sun Apr  7 04:16:14 2024
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`User`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`User` ;

CREATE TABLE IF NOT EXISTS `mydb`.`User` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `firstName` VARCHAR(45) NOT NULL,
  `lastName` VARCHAR(45) NOT NULL,
  `contactPhoneNumber` VARCHAR(9) NOT NULL,
  `email` VARCHAR(45) NULL,
  `dateOfBirth` VARCHAR(45) NOT NULL,
  `password` VARCHAR(60) NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `idUser_UNIQUE` (`id` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Office Manager`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`Office Manager` ;

CREATE TABLE IF NOT EXISTS `mydb`.`Office Manager` (
  `userId` INT NOT NULL,
  PRIMARY KEY (`userId`),
  CONSTRAINT `fk_Office Manager_User1`
    FOREIGN KEY (`userId`)
    REFERENCES `mydb`.`User` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Dentist`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`Dentist` ;

CREATE TABLE IF NOT EXISTS `mydb`.`Dentist` (
  `specialization` VARCHAR(45) NOT NULL,
  `userId` INT NOT NULL,
  PRIMARY KEY (`userId`),
  CONSTRAINT `fk_Dentist_User1`
    FOREIGN KEY (`userId`)
    REFERENCES `mydb`.`User` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Patient`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`Patient` ;

CREATE TABLE IF NOT EXISTS `mydb`.`Patient` (
  `mailingAddress` VARCHAR(255) NOT NULL,
  `userId` INT NOT NULL,
  PRIMARY KEY (`userId`),
  CONSTRAINT `fk_Patient_User1`
    FOREIGN KEY (`userId`)
    REFERENCES `mydb`.`User` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Request`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`Request` ;

CREATE TABLE IF NOT EXISTS `mydb`.`Request` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `type` ENUM('CALLIN', 'WEBSITE') NOT NULL,
  `status` TINYINT NULL,
  `patientId` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_Request_Patient1_idx` (`patientId` ASC) VISIBLE,
  UNIQUE INDEX `id_UNIQUE` (`id` ASC) VISIBLE,
  CONSTRAINT `fk_Request_Patient1`
    FOREIGN KEY (`patientId`)
    REFERENCES `mydb`.`Patient` (`userId`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Surgery`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`Surgery` ;

CREATE TABLE IF NOT EXISTS `mydb`.`Surgery` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NOT NULL,
  `state` VARCHAR(45) NOT NULL,
  `city` VARCHAR(45) NOT NULL,
  `street` VARCHAR(45) NOT NULL,
  `zipCode` VARCHAR(45) NOT NULL,
  `telephoneNumber` VARCHAR(9) NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Appointment`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`Appointment` ;

CREATE TABLE IF NOT EXISTS `mydb`.`Appointment` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `dentistId` INT NOT NULL,
  `patientId` INT NOT NULL,
  `surgeryId` INT NOT NULL,
  `date` DATETIME NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_Appointment_Dentist1_idx` (`dentistId` ASC) VISIBLE,
  INDEX `fk_Appointment_Patient1_idx` (`patientId` ASC) VISIBLE,
  UNIQUE INDEX `id_UNIQUE` (`id` ASC) VISIBLE,
  INDEX `fk_Appointment_Surgery1_idx` (`surgeryId` ASC) VISIBLE,
  CONSTRAINT `fk_Appointment_Dentist1`
    FOREIGN KEY (`dentistId`)
    REFERENCES `mydb`.`Dentist` (`userId`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Appointment_Patient1`
    FOREIGN KEY (`patientId`)
    REFERENCES `mydb`.`Patient` (`userId`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Appointment_Surgery1`
    FOREIGN KEY (`surgeryId`)
    REFERENCES `mydb`.`Surgery` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Bill`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`Bill` ;

CREATE TABLE IF NOT EXISTS `mydb`.`Bill` (
  `appointmentId` INT NOT NULL,
  `total` DOUBLE NOT NULL,
  `dueDate` DATETIME NOT NULL,
  `isPaid` TINYINT NOT NULL,
  PRIMARY KEY (`appointmentId`),
  INDEX `fk_Bill_Appointment1_idx` (`appointmentId` ASC) VISIBLE,
  CONSTRAINT `fk_Bill_Appointment1`
    FOREIGN KEY (`appointmentId`)
    REFERENCES `mydb`.`Appointment` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
