services:
  app:
    build:
      context: .
    platform: linux/x86_64
    restart: on-failure
    ports:
      - "8080:8080"
    environment:
      SERVER_PORT: 8080
      SPRING_APPLICATION_NAME: "appointment-management-app"
      SPRING_MVC_PATHMATCH_MATCHING_STRATEGY: ant_path_matcher

      SPRING_JPA_HIBERNATE_DDL_AUTO: create
      SPRING_JPA_SHOW_SQL: "true"
      SPRING_JPA_PROPERTIES_HIBERNATE_DIALECT: "org.hibernate.dialect.MySQL8Dialect"
      SPRING_JPA_GENERATE_DDL: "true"
      SPRING_BATCH_JDBC_INITIALIZE_SCHEMA: ALWAYS

      SPRING_SQL_INIT_MODE: always

      SPRING_DATASOURCE_URL: "jdbc:mysql://db:3307/cs489-apsd-appointmentmanagementapp-db?useSSL=false&allowPublicKeyRetrieval=true"
      SPRING_DATASOURCE_USERNAME: "root"
      SPRING_DATASOURCE_PASSWORD: "root"

      SPRING_DATASOURCE_DRIVE_CLASS_NAME: "com.mysql.cj.jdbc.Driver"

  db:
    image: mysql
    restart: unless-stopped
    ports:
      - "3307:3307"
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: cs489-apsd-appointmentmanagementapp-db
      MYSQL_TCP_PORT: 3307
    volumes:
      - ./db-data:/var/lib/mysql
volumes:
  db-data: